// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class AuditLog
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Action { get; set; }

    public string Entity { get; set; }

    public int? EntityId { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string IpAddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}