// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class EventAttendee
{
    public int Id { get; set; }

    public int EventId { get; set; }

    public int UserId { get; set; }

    public string Status { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}