// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class FollowedVenue
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int VenueId { get; set; }

    public virtual User User { get; set; }

    public virtual Venue Venue { get; set; }
}