// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class PaymentLog
{
    public int Id { get; set; }

    public int PaymentId { get; set; }

    public string Status { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Payment Payment { get; set; }
}