// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class Promotion
{
    public int Id { get; set; }

    public int? VenueId { get; set; }

    public int? EventId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? DiscountPercentage { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual Event Event { get; set; }

    public virtual Venue Venue { get; set; }
}