// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class ReservationStatusHistory
{
    public int Id { get; set; }

    public int ReservationId { get; set; }

    public string Status { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual Reservation Reservation { get; set; }
}