// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class Reservation
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int VenueId { get; set; }

    public int? TableId { get; set; }

    public int? EventId { get; set; }

    public DateTime ReservationDate { get; set; }

    public int NumberOfPeople { get; set; }

    public string Status { get; set; }

    public string SpecialRequests { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<ReservationStatusHistory> ReservationStatusHistories { get; set; } = new List<ReservationStatusHistory>();

    public virtual VenueTable Table { get; set; }

    public virtual User User { get; set; }

    public virtual Venue Venue { get; set; }
}