// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class StoredFile
{
    public int Id { get; set; }

    public string Entity { get; set; }

    public int EntityId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public int? FileSize { get; set; }

    public int? UploadedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User UploadedByNavigation { get; set; }
}