// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class VenueAnalytic
{
    public int Id { get; set; }

    public int VenueId { get; set; }

    public int? TotalReservations { get; set; }

    public decimal? TotalRevenue { get; set; }

    public int? TotalEvents { get; set; }

    public virtual Venue Venue { get; set; }
}