// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrishtinaNights.Core.Models;

public partial class Venue
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public int OwnerId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<FollowedVenue> FollowedVenues { get; set; } = new List<FollowedVenue>();

    public virtual User Owner { get; set; }

    public virtual ICollection<Promotion> Promotions { get; set; } = new List<Promotion>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<VenueAnalytic> VenueAnalytics { get; set; } = new List<VenueAnalytic>();

    public virtual ICollection<VenueOpeningHour> VenueOpeningHours { get; set; } = new List<VenueOpeningHour>();

    public virtual ICollection<VenueStaff> VenueStaffs { get; set; } = new List<VenueStaff>();

    public virtual ICollection<VenueTable> VenueTables { get; set; } = new List<VenueTable>();
}